#!/usr/bin/env bash
set -euo pipefail
shopt -s inherit_errexit shift_verbose extglob nullglob

# Generate manpage for rtfm from embedded template

declare -r SCRIPT_NAME="${0##*/}"
declare -- SCRIPT_DIR
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
readonly -- SCRIPT_DIR
declare -r MANPAGE_FILE="${SCRIPT_DIR}/rtfm.1"

# Function to display usage
usage() {
  cat >&2 <<EOF
Usage: ${SCRIPT_NAME} [OPTIONS]

Generate manpage for rtfm

Options:
  -i, --install    Install the generated manpage to system location
  -h, --help       Display this help message

Examples:
  ${SCRIPT_NAME}              # Generate rtfm.1 manpage
  ${SCRIPT_NAME} --install    # Generate and install manpage
EOF
}

# Function to check if running with sufficient privileges
can_sudo() {
  if [[ $EUID -eq 0 ]]; then
    return 0
  elif command -v sudo &>/dev/null && sudo -n true 2>/dev/null; then
    return 0
  else
    return 1
  fi
}

# Function to extract version from rtfm script
get_version() {
  if [[ -f "${SCRIPT_DIR}/rtfm" ]]; then
    grep -oP "VERSION='\\K[^']+" "${SCRIPT_DIR}/rtfm" 2>/dev/null || echo "1.2.0"
  else
    echo "1.2.0"
  fi
}

# Function to generate manpage
generate_manpage() {
  local -- version month_year
  version=$(get_version)
  month_year=$(date '+%B %Y')

  cat > "$MANPAGE_FILE" <<EOF
.\\" Manpage for rtfm
.\\" Generated by rtfm-manpage.sh
.TH RTFM 1 "${month_year}" "rtfm ${version}" "User Commands"
.SH NAME
rtfm \\- Read The Fucking Manuals
.SH SYNOPSIS
.B rtfm
[\\fIOPTIONS\\fR] \\fIcommand\\fR
.SH DESCRIPTION
A unified Linux documentation lookup tool that consolidates help information
from multiple sources into a single, easy-to-use interface.
.PP
The
.B rtfm
program searches for documentation across multiple help systems in priority
order, concatenating all found results for comprehensive coverage:
.PP
.RS
1. Bash builtin help \\- Internal shell commands (cd, alias, declare, etc.)
.br
2. Man pages \\- System documentation from all manpath directories
.br
3. Info pages \\- GNU project documentation (often more detailed)
.br
4. TLDR pages \\- Simplified examples and common usage patterns
.br
5. Command --help \\- Fallback for scripts with --help support
.RE
.PP
All found documentation is concatenated with page breaks and displayed
through a pager (less) for easy navigation.
.SH OPTIONS
.TP
.BR \\-r ", " \\-\\-rebuild\\-lists
Rebuild command indices from all documentation sources (requires sudo)
.TP
.BR \\-\\-install ", " \\-\\-update
Install or update rtfm, md2ansi, and tldr from GitHub (requires sudo and git)
.TP
.BR \\-v ", " \\-\\-verbose
Enable verbose output during operations (default)
.TP
.BR \\-q ", " \\-\\-quiet
Suppress verbose messages during operations
.TP
.BR \\-V ", " \\-\\-version
Display version information
.TP
.BR \\-h ", " \\-\\-help
Show help message
.SH ENVIRONMENT
.TP
.B NO_COLOR
Disable all ANSI color output (any value)
.TP
.B FORCE_COLOR
Force color output even when redirected to file or pipe
.TP
.B CLICOLOR_FORCE
Alternative to FORCE_COLOR (same effect)
.PP
Color output is automatically disabled when stdout is redirected to a file
or pipe. Use FORCE_COLOR=1 to override. Error messages to stderr have
independent TTY detection.
.SH FEATURES
.IP \\(bu 2
Multi-source search with intelligent fallback
.IP \\(bu 2
Fast O(1) lookups using pre-built indices
.IP \\(bu 2
Smart color detection (auto-disables for redirected output)
.IP \\(bu 2
Automatic detection of new man pages
.IP \\(bu 2
SHA256 checksum verification for secure updates
.IP \\(bu 2
Enhanced markdown formatting with md2ansi
.IP \\(bu 2
Integrated pagination with less
.SH EXAMPLES
.TP
.B rtfm rsync
Look up documentation for rsync (finds man page + tldr examples)
.TP
.B rtfm declare
Get help for bash's declare builtin
.TP
.B rtfm coreutils
View comprehensive GNU coreutils documentation
.TP
.B rtfm find
Search for find command usage
.TP
.B sudo rtfm --update
Update rtfm and all dependencies from GitHub
.TP
.B sudo rtfm -r
Rebuild documentation indices after installing new packages
.TP
.B NO_COLOR=1 rtfm ls
Disable colors explicitly
.TP
.B FORCE_COLOR=1 rtfm ls >/tmp/out.txt
Force colors when redirecting (useful for HTML conversion)
.SH FILES
.TP
.I /usr/local/bin/rtfm
Main executable
.TP
.I /usr/local/share/rtfm/builtin.list
Bash builtins index
.TP
.I /usr/local/share/rtfm/man.list
Man pages index
.TP
.I /usr/local/share/rtfm/info.list
Info pages index
.TP
.I /usr/local/share/rtfm/tldr.list
TLDR pages index
.PP
Run
.B rtfm --rebuild-lists
to generate or update these files.
.SH SECURITY
.IP \\(bu 2
Input validation prevents command injection (whitelist + dangerous pattern rejection)
.IP \\(bu 2
PATH locked to /usr/local/bin:/usr/bin:/bin
.IP \\(bu 2
SHA256 checksum verification during updates
.IP \\(bu 2
Secure temp files via mktemp (prevents symlink attacks)
.IP \\(bu 2
Automatic rollback on failed installations
.IP \\(bu 2
Privilege checks via can_sudo() before elevated operations
.SH INSTALLATION
The easiest way to install rtfm and dependencies:
.PP
.nf
# One-liner installation
wget https://raw.githubusercontent.com/Open-Technology-Foundation/rtfm/main/rtfm \\\\
  && chmod +x rtfm && sudo ./rtfm --install
.fi
.PP
This will automatically install:
.IP \\(bu 2
git (if not already installed)
.IP \\(bu 2
rtfm (documentation lookup utility)
.IP \\(bu 2
md2ansi (markdown to terminal converter)
.IP \\(bu 2
tldr pages (simplified command examples)
.SH DEPENDENCIES
.SS Required
.TP
.B bash
(5.2+) Script execution environment
.TP
.B grep
Searching through documentation lists
.TP
.B less
Paginated viewing
.TP
.B man
Man page system
.TP
.B info
GNU info system
.SS Optional (Installed Automatically)
.TP
.B git
For installation/updates
.TP
.B tldr
Simplified command examples
.TP
.B md2ansi
Enhanced markdown formatting
.TP
.B sha256sum
Checksum verification (recommended)
.TP
.B file
Detecting script types in --help fallback
.SH LICENSE
GNU General Public License v3.0
.SH AUTHOR
Open Technology Foundation
.br
https://github.com/Open-Technology-Foundation/rtfm
.SH SEE ALSO
.BR man (1),
.BR info (1),
.BR help (1),
.BR tldr (1)
EOF

  echo "${SCRIPT_NAME}: Generated manpage: $MANPAGE_FILE"
}

# Function to install manpage
install_manpage() {
  local -- man_dir='/usr/local/share/man/man1'

  if ! can_sudo; then
    >&2 echo "${SCRIPT_NAME}: Error: Installation requires sudo privileges"
    >&2 echo "Please run: sudo ${SCRIPT_NAME} --install"
    exit 1
  fi

  # Create man directory if it doesn't exist
  if [[ $EUID -eq 0 ]]; then
    mkdir -p "$man_dir"
    cp "$MANPAGE_FILE" "${man_dir}/rtfm.1"
    chmod 644 "${man_dir}/rtfm.1"
  else
    sudo mkdir -p "$man_dir"
    sudo cp "$MANPAGE_FILE" "${man_dir}/rtfm.1"
    sudo chmod 644 "${man_dir}/rtfm.1"
  fi

  # Update man database if mandb is available
  if command -v mandb &>/dev/null; then
    echo "${SCRIPT_NAME}: Updating man database..."
    if [[ $EUID -eq 0 ]]; then
      mandb -q
    else
      sudo mandb -q
    fi
  fi

  echo "${SCRIPT_NAME}: Manpage installed to: ${man_dir}/rtfm.1"
  echo "${SCRIPT_NAME}: You can now use: man rtfm"
}

# Main function
main() {
  local -i install=0

  # Parse arguments
  while (($#)); do
    case "$1" in
      -i|--install)
        install=1
        ;;
      -h|--help)
        usage
        exit 0
        ;;
      *)
        >&2 echo "${SCRIPT_NAME}: Unknown option: $1"
        usage
        exit 1
        ;;
    esac
    shift
  done

  # Generate manpage
  generate_manpage

  # Install if requested
  if ((install)); then
    install_manpage
  fi
}

main "$@"
#fin
